FROM public.ecr.aws/lambda/python:3.9

ARG BASE_URL
ARG RKS_PRIVATE_KEY
ARG RKS_PROJECT_ID
ARG RKS_SERVICE_ACCOUNT
ARG UH_API_TOKEN
ARG UH_PARTNER_SHARING_CODE
ARG S3_BUCKET
ARG S3_PREFIX
ARG BASE_URL_UH
ARG EMAIL_SENDER
ARG EMAIL_RECIPIENT_1
ARG EMAIL_RECIPIENT_2

ENV BASE_URL=$BASE_URL
ENV RKS_PRIVATE_KEY=$RKS_PRIVATE_KEY
ENV RKS_PROJECT_ID=$RKS_PROJECT_ID
ENV RKS_SERVICE_ACCOUNT=$RKS_SERVICE_ACCOUNT
ENV UH_API_TOKEN=$UH_API_TOKEN
ENV UH_PARTNER_SHARING_CODE=$UH_PARTNER_SHARING_CODE
ENV S3_BUCKET=$S3_BUCKET
ENV S3_PREFIX=$S3_PREFIX
ENV BASE_URL_UH=$BASE_URL_UH
ENV EMAIL_SENDER=$EMAIL_SENDER
ENV EMAIL_RECIPIENT_1=$EMAIL_RECIPIENT_1
ENV EMAIL_RECIPIENT_2=$EMAIL_RECIPIENT_2

WORKDIR /var/task

COPY requirements.txt .
RUN pip uninstall jwt PyJWT
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD "jitai_logic.lambda_handler"
